### ISSUE TITLE
Update Roadmap for align goals with CZI Proposals

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh.org#16]
- [ ] Add "Better support of Open Geospatial data formats" (EOSS)
- [ ] Add "Better support for large streaming gridded data support" (EOSS)
- [ ] Improve contributor / end-user diversity (DEI)
- [ ] Better accessibility / sharing / data export (DEI...)
